// Generated by scripts/generate_presentation.py; edit packages/presentation/tokens.json.
package com.suzent.mobile

object PresentationTokens {
    const val black: Long = 0xFF000000
    const val white: Long = 0xFFFFFFFF
    const val blue: Long = 0xFF0066FF
    const val green: Long = 0xFFA8E6A3
    const val yellow: Long = 0xFFFFE666
    const val red: Long = 0xFFFF0000
    const val gray: Long = 0xFF333333
    const val code_bg: Long = 0xFFf5f5f5
    const val code_text: Long = 0xFF1a1a1a
    const val borderWidth = 2
    const val shadowOffset = 2
    val ignoredToolNames = listOf("final_answer", "final answer")
    val compactionSummaryMarkers = listOf("[CONTEXT SUMMARY — READ BEFORE RESPONDING]", "--- ARCHIVED CONTEXT SUMMARY ---")
}
