name: Build Desktop Apps

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write


jobs:
  # Extract release notes from CHANGELOG.md
  changelog:
    runs-on: ubuntu-latest
    outputs:
      release_notes: ${{ steps.changelog.outputs.changes }}
      version: ${{ steps.changelog.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Read Changelog
        id: changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ github.ref_name }}
          path: ./CHANGELOG.md

  build:
    timeout-minutes: 90
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri -> target
          cache-on-failure: true

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev \
            libappindicator3-dev librsvg2-dev patchelf libsoup-3.0-dev javascriptcoregtk-4.1-dev

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-python-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install Python dependencies
        run: |
          pip install nuitka ordered-set zstandard
          pip install .

      - name: Cache Tauri CLI
        id: cache-tauri-cli
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/cargo-tauri*
          key: ${{ runner.os }}-tauri-cli-2.0
          restore-keys: |
            ${{ runner.os }}-tauri-cli-

      - name: Install Tauri CLI
        if: steps.cache-tauri-cli.outputs.cache-hit != 'true'
        run: cargo install tauri-cli --version '^2.0.0'

      - name: Cache frontend node_modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Cache Python backend build
        uses: actions/cache@v4
        with:
          path: |
            src-tauri/binaries/*.exe
            src-tauri/binaries/*.bin
            src-tauri/binaries/suzent-backend*
          key: ${{ runner.os }}-backend-${{ hashFiles('suzent/**/*.py', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Build Python backend
        run: python scripts/build_backend.py

      - name: Build Tauri app
        run: |
          cd src-tauri
          cargo tauri build --target ${{ matrix.target }}

      # Upload build artifacts for the release job
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.target }}
          path: |
            src-tauri/target/${{ matrix.target }}/release/bundle/msi/*.msi
            src-tauri/target/${{ matrix.target }}/release/bundle/dmg/*.dmg
            src-tauri/target/${{ matrix.target }}/release/bundle/appimage/*.AppImage
          if-no-files-found: ignore

  # Create GitHub Release with all artifacts and changelog-based release notes
  release:
    needs: [changelog, build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: List artifacts
        run: find artifacts -type f || echo "No artifacts found"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.ref_name }}
          body: ${{ needs.changelog.outputs.release_notes }}
          files: |
            artifacts/**/*.msi
            artifacts/**/*.dmg
            artifacts/**/*.AppImage

