"""Generate native constants from the presentation source consumed by desktop."""

import argparse
import json
from pathlib import Path

from mobile_logo import logo_outputs

ROOT = Path(__file__).resolve().parents[1]


def outputs() -> dict[Path, str]:
    data = json.loads((ROOT / "packages/presentation/tokens.json").read_text())
    kotlin = "// Generated by scripts/generate_presentation.py; edit packages/presentation/tokens.json.\npackage com.suzent.mobile\n\nobject PresentationTokens {\n"
    swift = "// Generated by scripts/generate_presentation.py; edit packages/presentation/tokens.json.\npublic enum PresentationTokens {\n"
    for key, value in data["colors"].items():
        name = key.replace("-", "_")
        kotlin += f"    const val {name}: Long = 0xFF{value[1:]}\n"
        swift += f"    public static let {name}: UInt32 = 0x{value[1:]}\n"
    for key in (
        "borderWidth",
        "shadowOffset",
        "spaceSmall",
        "spaceMedium",
        "spacePage",
        "spaceLarge",
        "typeTitle",
        "typeBody",
        "typeCaption",
        "typeChat",
        "typeControl",
        "typeSection",
        "controlHeight",
        "sidebarWidth",
    ):
        kotlin += f"    const val {key} = {data[key]}\n"
        swift += f"    public static let {key}: Double = {data[key]}\n"
    for key in ("ignoredToolNames", "compactionSummaryMarkers"):
        values = ", ".join(json.dumps(value, ensure_ascii=False) for value in data[key])
        kotlin += f"    val {key} = listOf({values})\n"
        swift += f"    public static let {key}: [String] = [{values}]\n"
    return {
        **logo_outputs(ROOT),
        ROOT
        / "apps/android/app/src/main/java/com/suzent/mobile/PresentationTokens.kt": kotlin
        + "}\n",
        ROOT / "packages/SuzentCore/Sources/SuzentCore/PresentationTokens.swift": swift
        + "}\n",
        ROOT
        / "frontend/src/presentation.css": f"/* Generated by scripts/generate_presentation.py */\n:root {{\n  --suzent-yellow: {data['colors']['yellow'].lower()};\n}}\n",
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(
                    f"Stale generated presentation file: {path.relative_to(ROOT)}"
                )
        else:
            path.write_text(content)


if __name__ == "__main__":
    main()
