"""Generate native version settings independently of the desktop release."""

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def version_outputs(root: Path, build_number: int | None = None) -> dict[Path, str]:
    data = json.loads((root / "packages/mobile-contract/version.json").read_text())
    version = data["version"]
    build = data["build"] if build_number is None else build_number
    if not isinstance(version, str) or not re.fullmatch(
        r"(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)", version
    ):
        raise ValueError("Mobile version must be major.minor.patch")
    if type(build) is not int or not 1 <= build <= 2_100_000_000:
        raise ValueError("Mobile build number must be between 1 and 2100000000")
    return {
        root / "apps/ios/Config/Version.xcconfig": (
            "// Generated by scripts/generate_mobile_version.py.\n"
            f"MARKETING_VERSION = {version}\nCURRENT_PROJECT_VERSION = {build}\n"
        ),
        root / "apps/android/version.properties": (
            "# Generated by scripts/generate_mobile_version.py.\n"
            f"versionName={version}\nversionCode={build}\n"
        ),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--build-number", type=int)
    args = parser.parse_args()
    for path, content in version_outputs(ROOT, args.build_number).items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(
                    f"Stale mobile version settings: {path.relative_to(ROOT)}"
                )
        else:
            path.write_text(content)


if __name__ == "__main__":
    main()
